# Generated by Django 5.0.6 on 2024-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='created_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
