# Generated by Django 5.0.6 on 2024-05-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0002_userdetails_created_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrndRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=200, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('request_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_sended_user_id', to='assessment_app.userdetails')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_user_id', to='assessment_app.userdetails')),
            ],
        ),
    ]
